spring:
  application:
    name: HRBank-team1

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# Logging
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

#  h2:
#    console:
#      enabled: true

schedule:
  backup-cron: "0 0 0/1 * * *"

hrBank:
  repository:
    file-directory: files
